[project]
name = 'my-app-backend'
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.110",
    "sqlalchemy[asyncio]>=2.0",
    "aiosqlite",
    "asyncpg",
    "alembic",
    "redis[asyncio]",
    "pydantic-settings",
    "python-jose[cryptography]",
    "passlib[bcrypt]",
    "aiobotocore>=2.11.0",
    "psycopg2-binary",
]

[tool.setuptools.packages.find]
include = ["app*", "workers*"]

[project.optional-dependencies]
test = ["pytest", "pytest-asyncio", "pytest-cov", "httpx"]
dev = ["ruff", "mypy"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
