"""create_auth_tables

Revision ID: b19acbb59dd2
Revises: 400e7d8563f6
Create Date: 2026-03-21 22:02:51.137914

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "b19acbb59dd2"
down_revision: Union[str, Sequence[str], None] = "400e7d8563f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
